siteTitle: Axiom Data Science
siteUrl: 'https://axiom-website.netlify.com/'
siteDescription: >-
  Axiom Data Science is an informatics and software development firm focused on developing
  scalable solutions which can be leveraged across a variety of users, clients and institutions
  in order to make the best tools for data management, integration, and visualization.
googleTrackingId: ''
