backend:
  name: github
  repo: axiom-data-science/website

media_folder: static/assets
public_folder: assets

publish_mode: editorial_workflow
site_url: https://axiom-website.netlify.com/

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{ year }}-{{ month }}-{{ day }}-{{ slug }}"
    preview_path: blog/{{ slug }}
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
      - { name: featured, label: Featured, widget: object, required: false, fields: [
          { name: "featured_image", label: "Featured Image", widget: "image", required: false },
          { name: "featured_caption", label: "Featured Caption", widget: "text", required: false }
        ]}
      - { name: imageA, label: Image A, widget: object, required: false, fields: [
          { name: "imageA_image", label: "Image A Image", widget: "image", required: false },
          { name: "imageA_caption", label: "Image A Caption", widget: "text", required: false }
        ]}
      - { name: imageB, label: Image B, widget: object, required: false, fields: [
          { name: "imageB_image", label: "Image B Image", widget: "image", required: false },
          { name: "imageB_caption", label: "Image B Caption", widget: "text", required: false }
        ]}
      - { name: imageC, label: Image C, widget: object, required: false, fields: [
          { name: "imageC_image", label: "Image C Image", widget: "image", required: false },
          { name: "imageC_caption", label: "Image C Caption", widget: "text", required: false }
        ]}
      - { name: imageD, label: Image D, widget: object, required: false, fields: [
          { name: "imageD_image", label: "Image D Image", widget: "image", required: false },
          { name: "imageD_caption", label: "Image D Caption", widget: "text", required: false }
        ]}

  - name: portal_updates
    label: Portal Updates
    folder: content/updates/portal
    create: true
    slug: "{{ year }}-{{ month }}-{{ day }}-{{ slug }}"
    preview_path: portal/updates/{{ slug }}
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
      - { name: featured, label: Featured, widget: object, required: false, fields: [
          { name: "featured_image", label: "Featured Image", widget: "image", required: false },
          { name: "featured_caption", label: "Featured Caption", widget: "text", required: false }
        ]}
      - { name: imageA, label: Image A, widget: object, required: false, fields: [
          { name: "imageA_image", label: "Image A Image", widget: "image", required: false },
          { name: "imageA_caption", label: "Image A Caption", widget: "text", required: false }
        ]}
      - { name: imageB, label: Image B, widget: object, required: false, fields: [
          { name: "imageB_image", label: "Image B Image", widget: "image", required: false },
          { name: "imageB_caption", label: "Image B Caption", widget: "text", required: false }
        ]}
      - { name: imageC, label: Image C, widget: object, required: false, fields: [
          { name: "imageC_image", label: "Image C Image", widget: "image", required: false },
          { name: "imageC_caption", label: "Image C Caption", widget: "text", required: false }
        ]}
      - { name: imageD, label: Image D, widget: object, required: false, fields: [
          { name: "imageD_image", label: "Image D Image", widget: "image", required: false },
          { name: "imageD_caption", label: "Image D Caption", widget: "text", required: false }
        ]}

  - name: atn_updates
    label: ATN Updates
    folder: content/updates/atn
    create: true
    slug: "{{ year }}-{{ month }}-{{ day }}-{{ slug }}"
    preview_path: atn/updates/{{ slug }}
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
      - { name: featured, label: Featured, widget: object, required: false, fields: [
          { name: "featured_image", label: "Featured Image", widget: "image", required: false },
          { name: "featured_caption", label: "Featured Caption", widget: "text", required: false }
        ]}
      - { name: imageA, label: Image A, widget: object, required: false, fields: [
          { name: "imageA_image", label: "Image A Image", widget: "image", required: false },
          { name: "imageA_caption", label: "Image A Caption", widget: "text", required: false }
        ]}
      - { name: imageB, label: Image B, widget: object, required: false, fields: [
          { name: "imageB_image", label: "Image B Image", widget: "image", required: false },
          { name: "imageB_caption", label: "Image B Caption", widget: "text", required: false }
        ]}
      - { name: imageC, label: Image C, widget: object, required: false, fields: [
          { name: "imageC_image", label: "Image C Image", widget: "image", required: false },
          { name: "imageC_caption", label: "Image C Caption", widget: "text", required: false }
        ]}
      - { name: imageD, label: Image D, widget: object, required: false, fields: [
          { name: "imageD_image", label: "Image D Image", widget: "image", required: false },
          { name: "imageD_caption", label: "Image D Caption", widget: "text", required: false }
        ]}
