backend:
  name: github
  repo: axiom-data-science/website

media_folder: static/assets
public_folder: assets

publish_mode: editorial_workflow
site_url: https://axiom-website.netlify.com/

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{fields.slug}}"
    preview_path: blog/{{slug}}
    identifier_field: title
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "slug", label: "URL Slug", widget: "string" }
      - { name: "date",  label: "Date",  widget: "date" }
      - { name: "body",  label: "Body",  widget: "markdown" }
      - { name: "featured", label: "Featured", widget: "object", required: false, fields: [
          { name: "image", label: "Featured Image", widget: "image", required: false },
          { name: "caption", label: "Featured Caption", widget: "text", required: false }
        ]}
      - { name: "imageA", label: "Image A", widget: "object", required: false, fields: [
          { name: "image", label: "Image A Image", widget: "image", required: false },
          { name: "caption", label: "Image A Caption", widget: "text", required: false }
        ]}
      - { name: "imageB", label: "Image B", widget: "object", required: false, fields: [
          { name: "image", label: "Image B Image", widget: "image", required: false },
          { name: "caption", label: "Image B Caption", widget: "text", required: false }
        ]}
      - { name: "imageC", label: "Image C", widget: "object", required: false, fields: [
          { name: "image", label: "Image C Image", widget: "image", required: false },
          { name: "caption", label: "Image C Caption", widget: "text", required: false }
        ]}
      - { name: "imageD", label: "Image D", widget: "object", required: false, fields: [
          { name: "image", label: "Image D Image", widget: "image", required: false },
          { name: "caption", label: "Image D Caption", widget: "text", required: false }
        ]}

  - name: portal_updates
    label: Portal Updates
    folder: content/updates/portal
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{fields.slug}}"
    preview_path: portal/{{slug}}
    identifier_field: title
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "slug", label: "URL Slug", widget: "string" }
      - { name: "version", label: "Version", widget: "string", required: false }
      - { name: "date", label: "Date", widget: "date" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "featured", label: "Featured", widget: "object", required: false, fields: [
          { name: "image", label: "Featured Image", widget: "image", required: false },
          { name: "caption", label: "Featured Caption", widget: "text", required: false }
        ]}
      - { name: "imageA", label: "Image A", widget: "object", required: false, fields: [
          { name: "image", label: "Image A Image", widget: "image", required: false },
          { name: "caption", label: "Image A Caption", widget: "text", required: false }
        ]}
      - { name: "imageB", label: "Image B", widget: "object", required: false, fields: [
          { name: "image", label: "Image B Image", widget: "image", required: false },
          { name: "caption", label: "Image B Caption", widget: "text", required: false }
        ]}
      - { name: "imageC", label: "Image C", widget: "object", required: false, fields: [
          { name: "image", label: "Image C Image", widget: "image", required: false },
          { name: "caption", label: "Image C Caption", widget: "text", required: false }
        ]}
      - { name: "imageD", label: "Image D", widget: "object", required: false, fields: [
          { name: "image", label: "Image D Image", widget: "image", required: false },
          { name: "caption", label: "Image D Caption", widget: "text", required: false }
        ]}

  - name: atn_updates
    label: ATN Updates
    folder: content/updates/atn
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{fields.slug}}"
    preview_path: atn/{{slug}}
    identifier_field: title
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "slug", label: "URL Slug", widget: "string" }
      - { name: "version", label: "Version", widget: "string", required: false }
      - { name: "date", label: "Date", widget: "date" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "featured", label: "Featured", widget: "object", required: false, fields: [
          { name: "image", label: "Featured Image", widget: "image", required: false },
          { name: "caption", label: "Featured Caption", widget: "text", required: false }
        ]}
      - { name: "imageA", label: "Image A", widget: "object", required: false, fields: [
          { name: "image", label: "Image A Image", widget: "image", required: false },
          { name: "caption", label: "Image A Caption", widget: "text", required: false }
        ]}
      - { name: "imageB", label: "Image B", widget: "object", required: false, fields: [
          { name: "image", label: "Image B Image", widget: "image", required: false },
          { name: "caption", label: "Image B Caption", widget: "text", required: false }
        ]}
      - { name: "imageC", label: "Image C", widget: "object", required: false, fields: [
          { name: "image", label: "Image C Image", widget: "image", required: false },
          { name: "caption", label: "Image C Caption", widget: "text", required: false }
        ]}
      - { name: "imageD", label: "Image D", widget: "object", required: false, fields: [
          { name: "image", label: "Image D Image", widget: "image", required: false },
          { name: "caption", label: "Image D Caption", widget: "text", required: false }
        ]}

  - name: staff
    label: Staff
    folder: content/staff
    create: true
    slug: "{{name}}"
    preview_path: staff/{{slug}}
    identifier_field: name
    fields:
      - { name: "name", label: "Name", widget: "string" }
      - { name: "email", label: "Email", widget: "string" }
      - { name: "position", label: "Position", widget: "string" }
      - { name: "headshot", label: "Headshot", widget: "image" }
      - { name: "body", label: "Bio", widget: "markdown" }
      - { name: "funny", label: "Funny", widget: "object", required: false, fields: [
          { name: "headshot", label: "Funny Headshot", widget: "image", required: false },
          { name: "bio", label: "Funny Bio", widget: "markdown", required: false }
        ]}
