backend:
  name: github
  repo: axiom-data-science/website

media_folder: static/assets
public_folder: assets

publish_mode: editorial_workflow
site_url: https://axiom-website.netlify.com/

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    preview_path: blog/{{slug}}
    identifier_field: title
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date",  label: "Date",  widget: "date" }
      - { name: "body",  label: "Body",  widget: "markdown" }

  - name: portal_updates
    label: Portal Updates
    folder: content/updates/portal
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    preview_path: portal/{{slug}}
    identifier_field: title
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "version", label: "Version", widget: "string" }
      - { name: "date", label: "Date", widget: "date" }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: atn_updates
    label: ATN Updates
    folder: content/updates/atn
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    preview_path: atn/{{slug}}
    identifier_field: title
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "version", label: "Version", widget: "string" }
      - { name: "date", label: "Date", widget: "date" }
      - { name: "body", label: "Body", widget: "markdown" }
