backend:
  name: github
  repo: axiom-data-science/website

media_folder: static/assets
public_folder: assets

#publish_mode: editorial_workflow
site_url: https://axiom-website.netlify.com/

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{ year }}-{{ month }}-{{ day }}-{{ slug }}"
    #preview_path: blog/{{ slug }}
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Body, widget: markdown }
