backend:
  name: github
  repo: axiom-data-science/website
  squash_merges: true
  # commit_messages:
  #   create: Create {{collection}} “{{slug}}”
  #   update: Update {{collection}} “{{slug}}”
  #   delete: Delete {{collection}} “{{slug}}”
  #   uploadMedia: Upload “{{path}}”
  #   deleteMedia: Delete “{{path}}”

media_folder: static/assets
public_folder: assets

#publish_mode: editorial_workflow
#site_url: https://axiom-website.netlify.com/

# slug:
#   encoding: "ascii"
#   clean_accents: true

collections:

  - name: posts
    label: Post
    editor:
      preview: true
    folder: content/posts
    slug: "{{year}}-{{month}}-{{day}}_{{fields.slug}}"
    create: true
    identifier_field: title
    fields:
      - { label: Template, name: template, widget: hidden, default: PostPage }
      - { label: Title, name: title, widget: string }
      - { label: "Relative URL Slug", name: relslug, widget: string }
      - { label: Date, name: date, widget: date }
      - { label: Body, name: body, widget: markdown }
      - { name: featured, label: Featured, widget: object, required: false, fields: [
          { name: image, label: "Featured Image", widget: image, required: false },
          { name: caption, label: "Featured Caption", widget: text, required: false }
        ]}
      - label: 'Images'
        name: 'images'
        widget: 'list'
        required: false
        fields:
          - { name: image, label: Image, widget: image, required: true }
          - { name: caption, label: Caption, widget: text, required: false }
      - label: 'Categories'
        name: 'categories'
        widget: 'list'
        required: false
        fields:
          - label: 'Category'
            name: 'category'
            widget: 'relation'
            collection: 'blog'
            searchFields: ['title']
            valueField: 'title'

  - name: blog
    label: Blog
    editor:
      preview: false
    folder: content/blog
    create: true
    identifier_field: title
    fields:
      - { label: Template, name: template, widget: hidden, default: PostCategoryPage }
      - { label: Title, name: title, widget: string }
      - { label: "Relative URL Slug", name: relslug, widget: string }
      - { label: Subtitle, name: subtitle, widget: string, required: false }
      - { name: featured, label: Featured, widget: object, required: false, fields: [
          { name: image, label: "Featured Image", widget: image, required: false },
          { name: caption, label: "Featured Caption", widget: text, required: false }
        ]}

  - name: solutions
    label: Solutions
    editor:
      preview: true
    folder: content/solutions
    create: true
    identifier_field: title
    fields:
      - { label: Template, name: template, widget: hidden, default: SolutionCategoryPage }
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string, required: false }
      - { label: "Relative URL Slug", name: relslug, widget: string }
      - { label: Body, name: body, widget: markdown }
      - { name: featured, label: Featured, widget: object, required: false, fields: [
          { name: image, label: "Featured Image", widget: image, required: false },
          { name: caption, label: "Featured Caption", widget: text, required: false }
        ]}
      - label: 'Images'
        name: 'images'
        widget: 'list'
        required: false
        fields:
          - { name: image, label: Image, widget: image, required: true }
          - { name: caption, label: Caption, widget: text, required: false }
      - label: 'Categories'
        name: 'categories'
        widget: 'list'
        required: false
        fields:
          - label: 'Category'
            name: 'category'
            widget: 'relation'
            collection: 'solutionCategories'
            searchFields: ['title']
            valueField: 'title'

  - name: solutionCategories
    label: Solution Categories
    editor:
      preview: false
    folder: content/solutionCategories
    create: true
    identifier_field: title
    fields:
      - { label: Template, name: template, widget: hidden, default: SolutionCategoryPage }
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string, required: false }
      - { label: "URL Slug", name: slug, widget: string }
      - { label: Body, name: body, widget: markdown, required: false }
      - { name: featured, label: Featured, widget: object, required: false, fields: [
          { name: image, label: "Featured Image", widget: image, required: false },
          { name: caption, label: "Featured Caption", widget: text, required: false }
        ]}

  - name: staff
    label: Staff
    editor:
      preview: true
    folder: content/staff
    create: true
    slug: "{{name}}"
    identifier_field: name
    fields:
      - { name: "name", label: "Name", widget: "string" }
      - { name: "email", label: "Email", widget: "string" }
      - { name: "position", label: "Position", widget: "string" }
      - { name: "headshot", label: "Headshot", widget: "image" }
      - { name: "body", label: "Bio", widget: "markdown" }
      - { name: "funny", label: "Funny", widget: "object", required: false, fields: [
          { name: "headshot", label: "Funny Headshot", widget: "image", required: false },
          { name: "bio", label: "Funny Bio", widget: "markdown", required: false }
        ]}

  - name: clients
    label: Clients
    editor:
      preview: false
    folder: content/clients
    create: true
    slug: "{{fields.slug}}"
    identifier_field: name
    fields:
      - { name: "name", label: "Name", widget: "string" }
      - { name: "slug", label: "URL Slug", widget: "string" }
      - { name: "url",  label: "URL",  widget: "string" }
      - { name: "logo", label: "Logo", widget: "image" }
      - { name: "body", label: "Description", widget: "markdown", required: false }
      - { name: "display", label: "Display Where?", widget: "select", multiple: true, default: [ "Clients" ],
          options: [ "Clients", "Featured" ]
        }

  - name: locations
    label: Locations
    editor:
      preview: false
    create: true
    slug: "{{title}}"
    folder: content/locations
    identifier_field: title
    fields:
      - { label: Title,     name: title,     widget: string }
      - { label: Address1 , name: address1,  widget: string }
      - { label: Address2,  name: address2,  widget: string }
      - { label: Photo,     name: photo,     widget: image }
      - { label: Longitude, name: longitude, widget: number,    valueType: float }
      - { label: Latitude,  name: latitude,  widget: number,    valueType: float }
      - { label: MapsLink,  name: mapslink,  widget: string }
      - { label: Body,      name: body,      widget: markdown,  required: false }

  # Generic informational pages
  - name: info
    label: Information Page
    editor:
      preview: true
    create: true
    folder: content/info
    identifier_field: title
    fields:
      - { label: Template, name: template, widget: hidden, default: DefaultPage }
      - { label: "Relative URL Slug", name: relslug, widget: string }
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
      - { name: featured, label: Featured, widget: object, required: false, fields: [
          { name: image, label: "Featured Image", widget: image, required: false },
          { name: caption, label: "Featured Caption", widget: text, required: false }
        ]}
      - label: 'Images'
        name: 'images'
        widget: 'list'
        required: false
        fields:
          - { name: image, label: Image, widget: image, required: true }
          - { name: caption, label: Caption, widget: text, required: false }

  - name: 'settings'
    label: 'Settings'
    delete: false
    editor:
      preview: false
    files:
      - file: 'content/settings.yml'
        label: 'Global Settings'
        name: 'global-settings'
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site Url, name: siteUrl, widget: string, required: false }
          - {
              label: Site Description,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - {
              label: Google Analytics Tracking Id,
              name: googleTrackingId,
              widget: string,
              required: false,
            }

  - name: pages
    label: Page
    delete: false
    editor:
      preview: true

    files:

      # The about page, which loads the "locations" objects to display
      - file: content/pages/about.md
        label: About
        name: about-page
        fields:
          - { label: Template, name: template, widget: hidden, default: AboutPage }
          - { label: "URL Slug", name: slug, widget: hidden, default: 'about' }
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: "Featured Image", name: featuredImage, widget: "image" }
          - { label: Body, name: body, widget: markdown, required: false }

      # The page that lists the blog categories and allows searching all "posts"
      - file: content/pages/blog.md
        label: Blog Categories
        name: blog-page
        fields:
          - { label: Template, name: template, widget: hidden, default: PostCategoryPage }
          - { label: "URL Slug", name: slug, widget: hidden, default: 'blog' }
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: "Featured Image", name: featuredImage, widget: "image" }
          - { label: Body, name: body, widget: markdown, required: false }

      # Solutions page, listing all of the Solutions Categories
      - file: content/pages/solutions.md
        label: Solution Categories
        name: solution-category-page
        fields:
          - { label: Template, name: template, widget: hidden, default: SolutionCategoryPage }
          - { label: "URL Slug", name: slug, widget: hidden, default: 'solutions' }
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: "Featured Image", name: featuredImage, widget: "image" }
          - { label: Body, name: body, widget: markdown, required: false }

      # Clients page, which loads the 'clients' objects
      - file: content/pages/clients.md
        label: Clients
        name: clients-page
        fields:
          - { label: Template, name: template, widget: hidden, default: ClientsPage }
          - { label: "URL Slug", name: slug, widget: hidden, default: 'clients' }
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: "Featured Image", name: featuredImage, widget: "image" }
          - { label: Body, name: body, widget: markdown, required: false }

      # The home / main / index / landing page
      - file: content/pages/home.md
        label: Home
        name: home-page
        fields:
          - { label: Template, name: template, widget: hidden, default: HomePage }
          - { label: "URL Slug", name: slug, widget: hidden, default: '' }
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: Body, name: body, widget: markdown, required: false }
          # Images to cycle through in the header area
          - label: Images
            name: images
            widget: list
            required: false
            fields:
              - { name: image, label: Image, widget: "image", required: true }
              - { name: caption, label: Caption, widget: text, required: false }
